# -*- coding: utf-8 -*-
"""Language_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q0INP1DXkSEJIWvKHenEapc06d_I_94u
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk

df=pd.read_csv("language.csv")

df.shape

df.isnull().sum()

df.info()

df['language'].value_counts()

from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(df["Text"])
y=df["language"]

print(X,y)

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

print(y)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

user_input=input("Enter your Sentence: ")

predicted=classifier.predict(vectorizer.transform([user_input]))

print(le.inverse_transform(predicted))